### ISSUE TITLE
Code Splitting

### ISSUE THREAD

**Issue by sajison** [designfwd/fwd-boilerplate-theme#5]
To better optimize the code splitting, we need to seperate out the variables, mixins, placeholders out of the common.scss file and import them on individual sheets. This will allow the individual sheets to compile correctly so we don't have to import the common.scss file on each page and have duplicate styles

**Comment by benjatron** [comment]
Let's talk about the potential of breaking things out not just by page template but also by component

**Comment by benjatron** [comment]
The new flow should mitigate this and allow for inline-ish loading. Further testing is definitely necessary, but I'm going to close this out for now and we can revisit later if things look like they aren't working.
